steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/functions_cloudbuild', '.']
images:
- 'gcr.io/$PROJECT_ID/functions_cloudbuild'
# tags: ['cloud-builders-community']